### ISSUE TITLE
大佬帮我看看启动这个工具后，日志一直显示获取种子列表失败，然后也不工作

### ISSUE THREAD

**Issue by IMUrFaher** [xiaoyi510/qBittorrentAutoLimitShare#1]
2024/03/24 14:48:42 | stdout | 2024/03/24 06:48:42 开始等待下一轮检查 等待 10 s后执行
-- | -- | --
2024/03/24 14:48:42 | stdout | 2024/03/24 06:48:42 获取种子列表失败 invalid character 'G' looking for beginning of value
2024/03/24 14:48:42 | stdout | 2024/03/24 06:48:42 invalid character 'G' looking for beginning of valueGet "https://192.168.31.94:8085/api/v2/sync/maindata": EOF
2024/03/24 14:48:34 | stdout | 2024/03/24 06:48:34 开始扫描 第2次
2024/03/24 14:48:34 | stdout | 2024/03/24 06:48:34 ======================================
2024/03/24 14:48:26 | stdout | 2024/03/24 06:48:26 开始检测Cookie
2024/03/24 14:48:16 | stdout | 2024/03/24 06:48:16 开始等待下一轮检查 等待 10 s后执行
2024/03/24 14:48:16 | stdout | 2024/03/24 06:48:16 获取种子列表失败 invalid character 'G' looking for beginning of value
2024/03/24 14:48:16 | stdout | 2024/03/24 06:48:16 invalid character 'G' looking for beginning of valueGet "https://192.168.31.94:8085/api/v2/sync/maindata": EOF
2024/03/24 14:48:08 | stdout | 2024/03/24 06:48:08 开始扫描 第1次
2024/03/24 14:48:08 | stdout | 2024/03/24 06:48:08 ======================================
2024/03/24 14:48:08 | stdout |  
2024/03/24 14:48:08 | stdout |  
2024/03/24 14:48:08 | stdout | 2024/03/24 06:48:08 登录完成
2024/03/24 14:47:59 | stdout | 2024/03/24 06:47:59 开始检测Cookie
2024/03/24 14:47:59 | stdout | Port:8085
2024/03/24 14:47:59 | stdout | Url :192.168.31.94
2024/03/24 14:47:59 | stdout | 2024/03/24 06:47:59 配置服务器信息
2024/03/24 14:47:59 | stdout | 2024/03/24 06:47:59 初始化完成
2024/03/24 14:47:59 | stdout | >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2024/03/24 14:47:59 | stdout |  
2024/03/24 14:47:59 | stdout | By:包子 Blog:https://blog.52nyg.com
2024/03/24 14:47:59 | stdout |  
2024/03/24 14:47:59 | stdout | 欢迎使用qBit 自动限制分享率工具

**Comment by xiaoyi510** [comment]
地址写错了?
2024/03/24 06:48:42 无效字符'G'，寻找值的开头。获取"https://192.168.31.94:8085/api/v2/sync/maindata"：EOF
感觉通讯不了呢?

**Comment by IMUrFaher** [comment]
> 地址写错了? 2024/03/24 06:48:42 无效字符'G'，寻找值的开头。获取"[https://192.168.31.94:8085/api/v2/sync/maindata"：EOF](https://192.168.31.94:8085/api/v2/sync/maindata%22%EF%BC%9AEOF) 感觉通讯不了呢?

我才发现前面是https，把默认的ssl=1变成0就好了
